---
apiVersion: v1
kind: Namespace
metadata:
  name: petclinic-demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-petclinic
  name: spring-petclinic
  namespace: petclinic-demo
spec:
  imagePullSecrets:
  - name: harbor-registry
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - image: harbor.devvnocsymphony.com/java-spring/petclinic:65
        imagePullPolicy: Always
        name: spring-petclinic

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-petclinic
  name: spring-petclinic
  namespace: petclinic-demo
spec:
  ports:
  - name: spring-petclinic
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: spring-petclinic
  type: LoadBalancer
